library(dplyr)
library(here)
here()
disasterdata <- read.csv(here("Original", "disaster.csv"), header = TRUE)
# Filter the data for the years 2000 to 2019 and disaster types "Earthquake" and "Drought"
subset_data <- disasterdata %>% filter(Year >= 2000 & Year <= 2019 & Disaster.Type %in% c("Earthquake", "Drought"))
names(disasterdata)
subset_data <- subset_data %>% select(Year, ISO, Disaster.Type)
subset_data <- subset_data %>% mutate(drought = ifelse(Disaster.Type == "Drought", 1, 0),earthquake = ifelse(Disaster.Type == "Earthquake", 1, 0))
summarized_data <- subset_data %>% group_by(Year, ISO) %>% summarize(drought = max(drought),earthquake = max(earthquake)) %>% ungroup()