---
title: "Week 8 In-class"
author: "Hamda Altaf"
date: "2024-10-28"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Creating a table for only the binary armed conflict specification

```{r}
attach(analyticaldata) # to tell R to use this data for following commands
analyticaldata$pctpopdens <- analyticaldata$popdens / 100 
loggdp <- log(gdp1000)   
preds <- as.formula(" ~ conflict + log(gdp1000) + OECD + pctpopdens + urban + 
                  agedep + male_edu + temp + rainfall1000 + earthquake + drought + 
                  ISO + as.factor(year)")
Matmormod <- plm(update.formula(preds, Matmor ~ .), index= c("ISO", "year"), effect="twoways", model="within",data = analyticaldata) # use plm 
Under5mormod <- plm(update.formula(preds, Under5mor ~ .),index= c("ISO", "year"), effect="twoways", model="within",data = analyticaldata)
Infantmormod <- plm(update.formula(preds, Infantmor ~ .),index= c("ISO", "year"), effect="twoways", model="within", data = analyticaldata)
Neonatalmormod <- plm(update.formula(preds, Neonatmor ~ .),index= c("ISO", "year"), effect="twoways", model="within", data = analyticaldata)
screenreg(list(Matmormod,Under5mormod,Infantmormod,Neonatalmormod), custom.model.names = c("Maternal mortality", "Under 5 Mortality", "Infant Mortality", "Neonatal Mortality"))

```



